- name: import common nodeJS for user
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Install Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter

