- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Enable service nginx
  ansible.builtin.service:
    name: nginx
    enabled: yes

- name: Copy Roboshop config file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Copy Nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Clean old app content
  ansible.builtin.file:
    path: /user/share/nginx/html
    state: absent

- name: Create app directoty
  ansible.builtin.file:
    path: /user/share/nginx/html
    state: directory

- name: Unarchive a file that needs to be downloaded
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Restart service nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Install filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat


- name: Restart service filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes

- name: Install Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter