- name: Install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devl
    state: installed

- name: Include app prereq
  ansible.builtin.import_role:
    file: app_prereq.yml

- name: Install python dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: include schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: include systemd setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml